ZO-3546_Test_jmeter_locust
zAgile/dc-app-performance-toolkit pull request #4
Opened 2022-06-07 19:38 UTC by dcahuana

2022-10-26 18:44 UTC, jhuertas requested changes

2022-10-26 18:44 UTC, jhuertas commented on app/jira.yml
> +    load_executor: locust            # jmeter and locust are supported. jmeter by default.
set default jmeter

2022-10-26 18:44 UTC, jhuertas commented on app/jira.yml
> -    total_actions_per_hour: 54500   # number of total JMeter/Locust actions per hour
leave them as defaults for prod

2022-11-01 00:52 UTC, closed without merging

2022-11-01 00:52 UTC, dcahuana commented
close